### ISSUE TITLE
Inquiry regarding plugin logic

### ISSUE THREAD

**Issue by amiryo** [ajoberstar/reckon#143] opened 2020-07-26 14:12 UTC
**Background:**
I have 2 branches : "dev" and "master"
Once in a while dev merged into master
I would like to tag both dev and master branches with 1 final release.
For example (chronological advancement) :
dev - 1.0.0 (baseline version) 
dev - 1.1.0 -ms.1
dev - 1.1.0 -ms.2
master  - 1.1.0 -rc.1 
master  - 1.1.0 -rc.2
master  - 1.1.0 (this is the final version)

Is it the proper use of reckon plugin ? 
if not what is the proper way to use the plugin when one branch is merged into another branch?

[Please refer to this issue:  https://github.com/ajoberstar/reckon/issues/142](https://github.com/ajoberstar/reckon/issues/142)

**Comment by ajoberstar** [comment] 2022-02-11 19:06
Closing as duplicate of #142

**Closed as completed by ajoberstar** 2022-02-11 19:06 UTC
