### ISSUE TITLE
Provide a way to specify a release tag prefix to use

### ISSUE THREAD

**Issue by reinhapa** [ajoberstar/reckon#152] opened 2020-12-10 06:32 UTC
Is it possible to provide add a configurable prefix for the release tags? I got a couple  projects that require a a release tag scheme like the following examples:

- `release/x.x.x`
- `release/vx.x.x`
- 'vx.x.x'

Providing a prefix would enable those projects to also use this plugin by configuring the appropriate prefixes `release/`, `release/v` and `v` in this cases.

**Comment by ajoberstar** [comment] 2022-02-11 19:07
Closing as a duplicate of #54

**Closed as completed by ajoberstar** 2022-02-11 19:07 UTC

**Comment by reinhapa** [comment] 2022-02-11 20:55
@ajoberstar I do not see really the relation to #54 here... In my case do want to have my versions using a own version format. Is it possible to provide a custom parser/format function?

**Comment by ajoberstar** [comment] 2022-02-11 21:02
Sorry, they're different use cases with the same solution. Multiprojects like #54 also want a custom naming scheme to resolve their scenario.

**Comment by reinhapa** [comment] 2022-02-11 21:05
When I understand you correctly there is actually no way to do this right?

**Comment by ajoberstar** [comment] 2022-02-11 21:10
Yes, right now there is no way to do it. It would be an enhancement.
