### ISSUE TITLE
Multi-project

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [ajoberstar/reckon#155] opened 2021-02-01 08:39 UTC
Is there any guidance about how to use Reckon in a multi-project repo? For example, an Android module which generates multiple android apps with different versions via some flavor or some build variant.

Is it possible? Should be great to add support to this, maybe via prefixes in tags, samples: `free-1.0.0-alpha1`, `paid-1.0.0-rc1`.

If possible, enable GitHub discussions because I would like to ask this before creating an issue.

**Comment by ajoberstar** [comment] 2022-02-11 19:05
Closing as a duplicate of #54.

**Closed as completed by ajoberstar** 2022-02-11 19:05 UTC
