### ISSUE TITLE
Add possibility to pass to reckon custom origin via system or project props

### ISSUE THREAD

**Issue by daggerok** [ajoberstar/reckon#132] opened 2020-02-13 19:05 UTC
Hi,

Thank you for awesome plugin!

Is it possible to configure somehow different origin where reckon tag will be created and published?
Currently I do workaround in my automation CI like so:

```bash
./gradlew reckonTagCreate -Preckon.stage=final
git push ssh://git@my-gitlab.com:10022/my-group/my-repo.git --tags
./gradlew -S -Pdeploy -Prelease artifactoryPublish --build-cache
```

I cannot use reckon tag push task in my gitlab ci, its failing with gitlab-ci auth error related to wrong not permitted auth token... But, I do have configured permitted ssh access to repo for gitlab-runner user, So I would love to customize missing git stuff on a fly, for example:

```bash
./gradlew reckonTagPush artifactoryPublish -Preckon.stage=final \
    -Preckon.origin=ssh://git@my-gitlab.com:10022/my-group/my-repo.git
```

Please, let me know if we can implement this. Thanks!

---
Regards,
Max

**Comment by ajoberstar** [comment] 2020-02-14 02:42
I think this is a duplicate of #89 effectively. Please reopen if you disagree.

**Closed as completed by ajoberstar** 2020-02-14 02:42 UTC
Labels: duplicate

**Comment by daggerok** [comment] 2020-02-14 11:43
Hello,

Yes, looks like it's duplicate.

Have you done some investigations on that? Maybe I could contribute

As far as I see, you are using your groovy git implementation (grgit-core), so maybe you can quickly guide me what needs to be done?

---
Regards
